typedef enum
{
    LLI_ESC = 0, LLI_F1, LLI_F2, LLI_F3, LLI_F4, LLI_F5, LLI_F6, LLI_F7, LLI_F8, LLI_F9, LLI_F10, LLI_F11, LLI_F12, LLI_PRINTSCREEN, LLI_SCROLLLOCK, LLI_PAUSE,
    LLI_BACKTICK, LLI_1, LLI_2, LLI_3, LLI_4, LLI_5, LLI_6, LLI_7, LLI_8, LLI_9, LLI_0, LLI_HYPHEN, LLI_EQUALS, LLI_BACKSPACE, LLI_INSERT, LLI_HOME, LLI_PAGEUP,
    LLI_TAB, LLI_Q, LLI_W, LLI_E, LLI_R, LLI_T, LLI_Y, LLI_U, LLI_I, LLI_O, LLI_P, LLI_LEFTBRACKET, LLI_RIGHTBRACKET, LLI_BACKSLASH, LLI_DELETE, LLI_END, LLI_PAGEDOWN,
    LLI_CAPSLOCK, LLI_A, LLI_S, LLI_D, LLI_F, LLI_G, LLI_H, LLI_J, LLI_K, LLI_L, LLI_SEMICOLON, LLI_QUOTE, LLI_ENTER,
    LLI_LSHIFT, LLI_Z, LLI_X, LLI_C, LLI_V, LLI_B, LLI_N, LLI_M, LLI_COMMA, LLI_PERIOD, LLI_SLASH, LLI_RSHIFT, LLI_UP,
    LLI_LCTRL, LLI_LGUI, LLI_LALT, LLI_SPACE, LLI_RALT, LLI_FN, LLI_RGUI, LLI_RCTRL, LLI_LEFT, LLI_DOWN, LLI_RIGHT,
} lled_index;

lled_index lled_kctoi(uint16_t keycode);
